# Generated by Django 3.1.7 on 2021-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0310_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='sent_from_api',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_from_api',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
